# This file was generated by GoReleaser. DO NOT EDIT.
cask "govm" do
  version "0.2.6-rc2"

  on_macos do
    sha256 "7383568e5bd369cec19e4ed0338fd659d271b63f65d2324086016159fa84fe06"
    url "https://github.com/smileoniks-ctrl/govm/releases/download/v#{version}/govm_#{version}_Darwin_all.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "3047058e3efce5248093cbfc1d4d7640df6902be5b2671d7e5543076a8b1ed4d"
      url "https://github.com/smileoniks-ctrl/govm/releases/download/v#{version}/govm_#{version}_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1aa962068dcad044cbc41f11858ea9a7a4b1e6d701973ac69ddc129e22ffc917"
      url "https://github.com/smileoniks-ctrl/govm/releases/download/v#{version}/govm_#{version}_Linux_x86_64.tar.gz"
    end
  end

  name "govm"
  desc "GoVM - Go Version Manager"
  homepage "https://github.com/smileoniks-ctrl/govm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "govm"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/govm"]
    end
  end

  # No zap stanza required
end
