# This file was generated by GoReleaser. DO NOT EDIT.
cask "govm" do
  version "0.2.7-rc2"

  on_macos do
    sha256 "acaa72eedfa5468307e188574dc8e390625065e43e7adcb00c1cbf813b39d845"
    url "https://github.com/smileoniks-ctrl/govm/releases/download/v#{version}/govm_#{version}_Darwin_all.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "4d87eb330172abcc27eb584cb948e17b3c142f6097e5428b26000a427ca5ee2f"
      url "https://github.com/smileoniks-ctrl/govm/releases/download/v#{version}/govm_#{version}_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c728f9827036675a44c7b84d499f31532d6e86733a2e74cd161ce76cc66494de"
      url "https://github.com/smileoniks-ctrl/govm/releases/download/v#{version}/govm_#{version}_Linux_x86_64.tar.gz"
    end
  end

  name "govm"
  desc "GoVM - Go Version Manager"
  homepage "https://github.com/smileoniks-ctrl/govm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "govm"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/govm"]
    end
  end

  # No zap stanza required
end
