# This file was generated by GoReleaser. DO NOT EDIT.
cask "govm" do
  version "0.2.7-rc3"

  on_macos do
    sha256 "52b56ebd739f4966cd118c0808888d8d1484daa27ac350b3dfc14a50e212d90c"
    url "https://github.com/SmileOniks/govm/releases/download/v#{version}/govm_#{version}_Darwin_all.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "958482e8e9e967b0255daa3bf814416ba78bccb6b0ee9e1c9f5aa5e57ca11369"
      url "https://github.com/SmileOniks/govm/releases/download/v#{version}/govm_#{version}_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "45248ed407d4fd05d5c2a4cbc084a45ef2de3e57095a438bcaec539259bdb01e"
      url "https://github.com/SmileOniks/govm/releases/download/v#{version}/govm_#{version}_Linux_x86_64.tar.gz"
    end
  end

  name "govm"
  desc "GoVM - Go Version Manager"
  homepage "https://github.com/SmileOniks/govm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "govm"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/govm"]
    end
  end

  # No zap stanza required
end
